// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiFt7cscr_Ona7oifylTfozkrwuPnVDQ0',
    appId: '1:795259530655:web:5ba11eff487834e2a8a1aa',
    messagingSenderId: '795259530655',
    projectId: 'gomodiarect-9b1f0',
    authDomain: 'gomodiarect-9b1f0.firebaseapp.com',
    storageBucket: 'gomodiarect-9b1f0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEDFDM3y0SNg9UFVZII-o3WvOk5DvDh9o',
    appId: '1:795259530655:android:65fd040fc0440a57a8a1aa',
    messagingSenderId: '795259530655',
    projectId: 'gomodiarect-9b1f0',
    storageBucket: 'gomodiarect-9b1f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCheTkAUMSs_pi7EotICvFjPCitA9D9w1I',
    appId: '1:795259530655:ios:57b1510d46464c75a8a1aa',
    messagingSenderId: '795259530655',
    projectId: 'gomodiarect-9b1f0',
    storageBucket: 'gomodiarect-9b1f0.appspot.com',
    iosClientId: '795259530655-c16nfdk018ft4avk7f4mn7mrl6ssq8qo.apps.googleusercontent.com',
    iosBundleId: 'com.example.gomodiarect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCheTkAUMSs_pi7EotICvFjPCitA9D9w1I',
    appId: '1:795259530655:ios:57b1510d46464c75a8a1aa',
    messagingSenderId: '795259530655',
    projectId: 'gomodiarect-9b1f0',
    storageBucket: 'gomodiarect-9b1f0.appspot.com',
    iosClientId: '795259530655-c16nfdk018ft4avk7f4mn7mrl6ssq8qo.apps.googleusercontent.com',
    iosBundleId: 'com.example.gomodiarect',
  );
}
